doctrine_migrations:
    enable_profiler: false

when@dev:
    doctrine_migrations:
        migrations_paths:
            'DoctrineMigrations': '%kernel.project_dir%/migrations/sqlite'

when@prod:
    doctrine_migrations:
        migrations_paths:
            'DoctrineMigrations': '%kernel.project_dir%/migrations/mysql'