doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Administration:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Administration/Domain/Entity'
                prefix: 'App\Administration\Domain\Entity'
                alias: Administration
            Affiliate:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Site/Affiliate/Domain/Entity'
                prefix: 'App\Site\Affiliate\Domain\Entity'
                alias: Booking
            Booking:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Booking/Domain/Entity'
                prefix: 'App\Booking\Domain\Entity'
                alias: Booking
            Customer:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Customer/Domain/Entity'
                prefix: 'App\Customer\Domain\Entity'
                alias: Customer
            Page:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Site/Page/Domain/Entity'
                prefix: 'App\Site\Page\Domain\Entity'
                alias: Page
            Product:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Domain/Entity'
                prefix: 'App\Product\Domain\Entity'
                alias: Product

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
