twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bulma_layout.html.twig']
    globals:
        paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'

when@test:
    twig:
        strict_variables: true
