controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
controllersAffiliate:
    resource:
        path: ../src/Site/Affiliate/Application/Controller/
        namespace: App\Site\Affiliate\Application\Controller
    type: attribute
controllersBooking:
    resource:
        path: ../src/Booking/Application/Controller/
        namespace: App\Booking\Application\Controller
    type: attribute
controllersCustomer:
    resource:
        path: ../src/Customer/Application/Controller/
        namespace: App\Customer\Application\Controller
    type: attribute
controllersPage:
    resource:
        path: ../src/Site/Page/Application/Controller/
        namespace: App\Site\Page\Application\Controller
    type: attribute
controllersProduct:
    resource:
        path: ../src/Product/Application/Controller/
        namespace: App\Product\Application\Controller
    type: attribute