controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
controllersCart:
    resource:
        path: ../src/Cart/Application/Controller/
        namespace: App\Cart\Application\Controller
    type: attribute