name: BuildAndTest

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      extensions: gd intl zip
      key: cache-v1
      php-version: '8.2'
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          yarn install
          yarn build

      - name: Execute tests (edge-to-edge tests) via PHPUnit
        run: vendor/bin/phpunit --testsuite edge-to-edge --no-coverage
